---
- name: "Multiple task and print output"  # Name of the playbook describing what it does
  hosts: localhost                       # Target hosts to run on; here it's the local machine

  tasks:
    - name: "Check connection of host"  # Task to check if the host is reachable
      ping:                            # Uses the 'ping' module to test connectivity (no args needed)

    - name: "Print output"              # Task to print a message on the console
      debug:                          # Uses the 'debug' module to display messages
        msg: "HELLO WORLD!"           # The actual message to print
