---                                           # Start of YAML document
- name: Create and delete file and directory - basic operations  # Playbook description
  hosts: all                                  # Target all hosts in inventory
  become: true                                # Run tasks with sudo privileges

  tasks:                                     # List of tasks to execute

    # Ensure /personal directory exists
    - name: Create /personal directory if not present            # Task: create directory if missing
      file:                                                      # Using 'file' module to manage files/directories
        path: /personal                                         # Path of the directory
        state: directory                                        # Ensure it is a directory
        mode: '0755'                                           # Permissions: owner=rwx, group=rx, others=rx

    # Create file inside /personal
    - name: Create file /personal/fileName.txt                  # Task: create a file
      file:                                                    # Using 'file' module again
        path: /personal/fileName.txt                           # File path
        state: file                                           # Ensure it's a file
        mode: '0644'                                          # Permissions: owner=rw, group=r, others=r
        force: yes                                           # Force recreate if file exists (updates permissions)

    # Create subdirectory inside /personal
    - name: Create directory /personal/directoryName            # Task: create subdirectory
      file:                                                    # 'file' module again
        path: /personal/directoryName                          # Path of subdirectory
        state: directory                                       # Ensure it's a directory
        mode: '0777'                                          # Permissions: full access for all (read/write/execute)

    # Delete the file
    - name: Delete file /personal/fileName.txt                 # Task: remove the file
      file:                                                    # Using 'file' module
        path: /personal/fileName.txt                           # File to delete
        state: absent                                         # 'absent' means delete the file

    # Delete the directory
    - name: Delete directory /personal/directoryName            # Task: remove directory
      file:                                                    # Using 'file' module
        path: /personal/directoryName                          # Directory to delete
        state: absent                                         # Delete the directory
