---

- name: change user password
  hosts: all
  become: true
  tasks:
    - name: changing user password
      user:                                      # Using Ansible user module to manage users (required)
        name: user-02                            # Username whose password will be changed (required)
        update_password: always                   # When to update password:  1. always: update password every time play runs AND  2. on_create: update password only if user is created now (required)
        password: "{{'agdtyuimnb' | password_hash('sha512')}}"  # Encrypted password string (required)
